apiVersion: apps/v1
kind: Deployment
metadata:
  name: solar-system
  labels:
    app: solar-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: solar-system
  strategy: {}
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
      - name: solar-system
        image: thevenusian/solar:6c5a55242560757366e58cb26350dc94c3485b42
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: mongo-db-creds
              key: MONGO_URI
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-db-creds
              key: MONGO_USERNAME
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-db-creds
              key: MONGO_PASSWORD
