apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: mongo-db-credentials
  namespace: solar-system
spec:
  encryptedData:
    MONGO_PASSWORD: AgCEb8RXV8ZYFpOXhgjm1Ke/ks7jX8GRqa7PQMJ3eHGbgI4gWiOkyhTbI/gJ6YWpsQeM6ZtesEuHXFcHIPFqt/DK+aHjnAKdum2y0dG923ob94V1cZV86Zv0DQ3oi6KYAF/S8tII1mDQ2jDr0/3n9uuuxW8J06PKrM8FO9fG3sc2Cc5oclO8TT85+bHBQZuETQoE1pUyCo+Y92WeW8IgtLj2TuiHWrMZTiWc1uFduDZfgWWRus3tDUsnBtJtPf9Yl61x7FvlMG6whYSj5x7kPzt3F0jzauG+I+XCuY/KNFTy3YafMe08D9EwLdW9umh0Q6wUtOU8S0JvC6nhO+GazQHIYr8acIOSdamH1hRSkFfS7neTJYMPMXYmgrEeKBltf393SxppTl+L20ia/Ij1c9j5HAeAEQG1kMuqn2LYkEvhVr/6p6toxG2rxRNeanPAN1vcHksBSRvqcyKMvEhlBjTM5c7eazKkSamLIr/7Wd476tsC1mfOpMKJOoAcU0zi1bufOvFnEzIbBy801PObEjNoEeQTWTr22KS9uHgnJrELOf4cxBsmJkeLJx1NrXlQPnBk7MDKkZ7aoqMAXyckF2HFyU3O3sB59CsJpwmQhNDMHEpSr1xQTd1H2egy1DGN/tc+2ndFCfLW67T3+0UR0pxrai0Z3beP3//fnaj/iU++jmxMQ4lL1LamiZXoVfivpnROLpw=
    MONGO_URI: AgCyAWZbu14nJuL4Fv69Gp7PyEisU8XQs6ohq3YgNUY9BWqQDEAaHwsiWnxi7UdIYSVuqXXcnzQE8Lj2G27dLaNsvTXAi4an1MumTlI7tpsP6T/QtpNoWoAG+I9TWeT3KPRJPQFiGlxEWzh+Q6c6u+j0gPSrS82mhyo7lpxNWAbgdCY5Qaqc8yljaPeIdkDDrcybLTXrBLiPXNmdhiJN8WZaBlZ91f+PHMsQ/UobinnAh26p+1TO0+XbpJtG9fAZd9nAX+cC47PEyKSPR+ljNKJFHEDnXePJLF7MjDwOfRCVTmUn0rWVOsRKj81U7nekgl5euiv+ibjCQ6Ah7jVU5mvhROhnBsJ8xzmPwjr7KKsQFR/JdNSLRXmYIj6eL8o/UQi0kk3suXqI8z8bepYKKn84oVBs5m1nPfZ7fml5BWscQplR/lamK2YeRCTS5ri89dw5V6p/cVKC356bDetUbYpBNI75Kzz90JxrrRvtSiVrPWBxJMqCtmwXndUh9peTyDT2idw+joJ/7q+qzVKVgERL2n6Fylg94tKa6BOtRhK8yXQaboIhFulKnvuX37JqTrmYC6WDAato1Z5zN/3Xd0nalCmsBYi7aRQHB7Mv91LiWxG7Aa/RFH0fOxT5IDd+fBSGYSZ/V3fomiF3yB/5VcrxG4a64wy3l4JH7bN5KT0NPm2TxpMSH4sRmZ/eHL0lej8X6DbT2Q6FHet6aNqx2oLacnwju9DxJ7zfFO97PSSVuYKQX9V973kmiSsUmCMQy1t+Ko3AjSP0/IUAgDKdCSGJNDTbwsEpIGVqU17Bjztk
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: mongo-db-credentials
      namespace: solar-system

